import { Navbar } from '@/components/layout/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import Provider from '@/components/Provider';
import QueryWrapper from './QueryWrapper';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider>
          <QueryWrapper>
            <Navbar />
            {children}
          </QueryWrapper>
        </Provider>
      </body>
    </html>
  );
}
